.PHONY: initialize

initialize:
	sudo ./bin/mitamae local --log-level=debug mitamae/roles/initialize.rb

configure-mysql:
	sudo ./bin/mitamae local --log-level=debug mitamae/cookbooks/mysql/default.rb
